export const FETCH_VAKSIN_BY_ID_REQUEST = 'FETCH_VAKSIN_BY_ID_REQUEST';
export const FETCH_VAKSIN_BY_ID_SUCCESS = 'FETCH_VAKSIN_BY_ID_SUCCESS';
export const FETCH_VAKSIN_BY_ID_FAILURE = 'FETCH_VAKSIN_BY_ID_FAILURE';

export const UPDATE_VAKSIN_STATUS_REQUEST = 'UPDATE_VAKSIN_STATUS_REQUEST';
export const UPDATE_VAKSIN_STATUS_SUCCESS = 'UPDATE_VAKSIN_STATUS_SUCCESS';
export const UPDATE_VAKSIN_STATUS_FAILURE = 'UPDATE_VAKSIN_STATUS_FAILURE';